# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
twitter: &twitter
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>

development:
  secret_key_base: c1ef3d1ab85fa83e8f5310f5ddc0e324543f4be022c7570d67878ca69f35bf26e1848c66945ee006914b8466c67733993e40ea89690bea09338e25216cd90cfd
  <<: *twitter

test:
  secret_key_base: 9649c7760d51292274e0286f538c40e9e49196c368ae06edaaa8ae367d9db8d91cc599c03d95bdd8a4c4095b798abd66e1f4334593badaf0c4f67f09d131c8a3
  <<: *twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter
